#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/houses
#    username: root
#    password: 887933
spring:
  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/houses
    username: root
    password: 123456
    maxActive: 3 #最大连接数
    minIdle: 1   #最小连接数
    maxWait: 10000 #获取连接最大等待时间
    validationQuery: SELECT 'x'  #解决mysql8小时问题.mysql会主动超过8小时会断开连接
  freemarker:
    charset: UTF-8
    content-type: text/html;charset=utf-8
    expose-request-attributes: true #设定所有模板都有request域
    expose-session-attributes: true
    expose-spring-macro-helpers: true # requestContext域
    allow-session-override: true
    suffix: .ftl
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: utf-8
      auto_import: common/common.ftl as common
  mail:
    host: smtp.163.com
    username: xiaokainiucs@163.com
    password: qwk13882183772
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: 192.168.213.121
    port: 6379
    database: 3
    jedis:
      pool:
        max-active: 8 #z最大连接池
        max-wait: 1ms #连接池最大阻塞的时间
        max-idle: 4
        min-idle: 0  #连接池中最小空闲连接
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml


file:
  path: D:\img  #存储的到服务器的真实图片地址
  prefix: http://127.0.0.1:81/pic #是你访问图片服务器的虚拟地址

domain:
  name: 127.0.0.1:80

server:
  port: 80